# Generated by Django 2.2.7 on 2019-11-11 15:25

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photo.models._get_image_path)),
                ('title', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
